package Entidades;
// Generated 19/10/2009 12:36:38 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Abono generated by hbm2java
 */
public class Abono implements java.io.Serializable {

    private int id;
    private Factura factura;
    private Date fechaAbono;
    private double valor;

    public Abono() {
    }

    public Abono(int id, Factura factura, Date fechaAbono, double valor) {
        this.id = id;
        this.factura = factura;
        this.fechaAbono = fechaAbono;
        this.valor = valor;
    }

    public Abono(Factura factura, Date fechaAbono, double valor) {

        this.factura = factura;
        this.fechaAbono = fechaAbono;
        this.valor = valor;
    }

    public Abono(int id, Date fechaAbono, double valor) {
        this.id = id;
        this.fechaAbono = fechaAbono;
        this.valor = valor;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Factura getFactura() {
        return this.factura;
    }

    public void setFactura(Factura factura) {
        this.factura = factura;
    }

    public Date getFechaAbono() {
        return this.fechaAbono;
    }

    public void setFechaAbono(Date fechaAbono) {
        this.fechaAbono = fechaAbono;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }
}


