package Entidades;
// Generated 9/11/2009 04:46:57 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Adendo generated by hbm2java
 */
public class Adendo implements java.io.Serializable {

    private int id;
    private int idContrato;
    private Date fechaInicio;
    private Date fechaFin;

    public Adendo() {
    }

    public Adendo(int idContrato, Date fechaInicio, Date fechaFin) {
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    public Adendo(int id, int idContrato, Date fechaInicio, Date fechaFin) {
        this.id = id;
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdContrato() {
        return this.idContrato;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
}


