package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Integer codigo;
     private Set cuentaBancarias = new HashSet(0);


    public Banco(int id, String nombre, Integer codigo) {
       this.id = id;
       this.nombre = nombre;
       this.codigo = codigo;
    }
    public Banco() {
    }

    public Banco(int id) {
        this.id = id;
    }

	
    public Banco(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Banco(int id, String nombre, Integer codigo, Set cuentaBancarias) {
       this.id = id;
       this.nombre = nombre;
       this.codigo = codigo;
       this.cuentaBancarias = cuentaBancarias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Set getCuentaBancarias() {
        return this.cuentaBancarias;
    }
    
    public void setCuentaBancarias(Set cuentaBancarias) {
        this.cuentaBancarias = cuentaBancarias;
    }




}


