package Entidades;
// Generated 9/11/2009 07:01:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bonificacion generated by hbm2java
 */
public class Bonificacion  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double valor;
     private Date fechaIngreso;
     private boolean seleccionado;

    public Bonificacion() {
    }

    public Bonificacion(int id) {
        this.id = id;
    }
	
    public Bonificacion(int id, String nombre, double valor, Date fechaIngreso) {
        this.id = id;
        this.nombre = nombre;
        this.valor = valor;
        this.fechaIngreso = fechaIngreso;
    }
   
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    /**
     * @return the seleccionado
     */
    public boolean isSeleccionado() {
        return seleccionado;
    }

    /**
     * @param seleccionado the seleccionado to set
     */
    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }
    
}


