package Entidades;
// Generated 8/02/2010 03:33:06 PM by Hibernate Tools 3.2.1.GA



/**
 * CausacionEmpresa generated by hbm2java
 */
public class CausacionEmpresa  implements java.io.Serializable {


     private int id;
     private int diasCotizados;
     private double salud;
     private double pension;
     private double ibcRiesgos;
     private double riesgos;
     private double cesantias;
     private double interesesCesantias;
     private double ccf;
     private double sena;
     private double icbf;
     private double prima;
     private double vacaciones;
     private double otro1;
     private double otro2;
     private double total;
     private int idCausacionNomina;
     private double ibcEmpresa;

    public CausacionEmpresa(int diasCotizados, double salud, double pension, double ibcRiesgos, double riesgos, double cesantias, double interesesCesantias, double ccf, double sena, double icbf, double prima, double vacaciones, double total,double ibcEmpresa) {
        this.diasCotizados = diasCotizados;
        this.salud = salud;
        this.pension = pension;
        this.ibcRiesgos = ibcRiesgos;
        this.riesgos = riesgos;
        this.cesantias = cesantias;
        this.interesesCesantias = interesesCesantias;
        this.ccf = ccf;
        this.sena = sena;
        this.icbf = icbf;
        this.prima = prima;
        this.vacaciones = vacaciones;
        this.total = total;
        this.ibcEmpresa = ibcEmpresa;
    }

     

    public CausacionEmpresa() {
    }

    public CausacionEmpresa(int id, int diasCotizados, double salud, double pension, double ibcRiesgos, double riesgos, double cesantias, double interesesCesantias, double ccf, double sena, double icbf, double prima, double vacaciones, double otro1, double otro2, double total, int idCausacionNomina) {
       this.id = id;
       this.diasCotizados = diasCotizados;
       this.salud = salud;
       this.pension = pension;
       this.ibcRiesgos = ibcRiesgos;
       this.riesgos = riesgos;
       this.cesantias = cesantias;
       this.interesesCesantias = interesesCesantias;
       this.ccf = ccf;
       this.sena = sena;
       this.icbf = icbf;
       this.prima = prima;
       this.vacaciones = vacaciones;
       this.otro1 = otro1;
       this.otro2 = otro2;
       this.total = total;
       this.idCausacionNomina = idCausacionNomina;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDiasCotizados() {
        return this.diasCotizados;
    }
    
    public void setDiasCotizados(int diasCotizados) {
        this.diasCotizados = diasCotizados;
    }
    public double getSalud() {
        return this.salud;
    }
    
    public void setSalud(double salud) {
        this.salud = salud;
    }
    public double getPension() {
        return this.pension;
    }
    
    public void setPension(double pension) {
        this.pension = pension;
    }
    public double getIbcRiesgos() {
        return this.ibcRiesgos;
    }
    
    public void setIbcRiesgos(double ibcRiesgos) {
        this.ibcRiesgos = ibcRiesgos;
    }
    public double getRiesgos() {
        return this.riesgos;
    }
    
    public void setRiesgos(double riesgos) {
        this.riesgos = riesgos;
    }
    public double getCesantias() {
        return this.cesantias;
    }
    
    public void setCesantias(double cesantias) {
        this.cesantias = cesantias;
    }
    public double getInteresesCesantias() {
        return this.interesesCesantias;
    }
    
    public void setInteresesCesantias(double interesesCesantias) {
        this.interesesCesantias = interesesCesantias;
    }
    public double getCcf() {
        return this.ccf;
    }
    
    public void setCcf(double ccf) {
        this.ccf = ccf;
    }
    public double getSena() {
        return this.sena;
    }
    
    public void setSena(double sena) {
        this.sena = sena;
    }
    public double getIcbf() {
        return this.icbf;
    }
    
    public void setIcbf(double icbf) {
        this.icbf = icbf;
    }
    public double getPrima() {
        return this.prima;
    }
    
    public void setPrima(double prima) {
        this.prima = prima;
    }
    public double getVacaciones() {
        return this.vacaciones;
    }
    
    public void setVacaciones(double vacaciones) {
        this.vacaciones = vacaciones;
    }
    public double getOtro1() {
        return this.otro1;
    }
    
    public void setOtro1(double otro1) {
        this.otro1 = otro1;
    }
    public double getOtro2() {
        return this.otro2;
    }
    
    public void setOtro2(double otro2) {
        this.otro2 = otro2;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public int getIdCausacionNomina() {
        return this.idCausacionNomina;
    }
    
    public void setIdCausacionNomina(int idCausacionNomina) {
        this.idCausacionNomina = idCausacionNomina;
    }

    /**
     * @return the ibcEmpresa
     */
    public double getIbcEmpresa() {
        return ibcEmpresa;
    }

    /**
     * @param ibcEmpresa the ibcEmpresa to set
     */
    public void setIbcEmpresa(double ibcEmpresa) {
        this.ibcEmpresa = ibcEmpresa;
    }




}


