package Entidades;
// Generated 19/11/2009 09:41:40 PM by Hibernate Tools 3.2.1.GA



/**
 * CausPsBonificacion generated by hbm2java
 */
public class CausPsBonificacion  implements java.io.Serializable {


     private int id;
     private int idBonificacion;
     private int idCausacionPs;

    public CausPsBonificacion() {
    }

    public CausPsBonificacion(int id, int idBonificacion, int idCausacionPs) {
       this.id = id;
       this.idBonificacion = idBonificacion;
       this.idCausacionPs = idCausacionPs;
    }

    public CausPsBonificacion(int idBonificacion, int idCausacionPs) {
 
       this.idBonificacion = idBonificacion;
       this.idCausacionPs = idCausacionPs;
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdBonificacion() {
        return this.idBonificacion;
    }
    
    public void setIdBonificacion(int idBonificacion) {
        this.idBonificacion = idBonificacion;
    }
    public int getIdCausacionPs() {
        return this.idCausacionPs;
    }
    
    public void setIdCausacionPs(int idCausacionPs) {
        this.idCausacionPs = idCausacionPs;
    }




}


