package Entidades;
// Generated 9/11/2009 07:01:15 PM by Hibernate Tools 3.2.1.GA



/**
 * CausaNominaProvision generated by hbm2java
 */
public class CausaNominaProvision  implements java.io.Serializable {


     private int id;
     private Provisiones provisiones;
     private CausacionNomina causacionNomina;
     private double valor;

    public CausaNominaProvision() {
    }

    public CausaNominaProvision( CausacionNomina causacionNomina,Provisiones provisiones, double valor) {
       
       this.provisiones = provisiones;
       this.causacionNomina = causacionNomina;
       this.valor = valor;
    }
    public CausaNominaProvision(int id, Provisiones provisiones, CausacionNomina causacionNomina, double valor) {
       this.id = id;
       this.provisiones = provisiones;
       this.causacionNomina = causacionNomina;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Provisiones getProvisiones() {
        return this.provisiones;
    }
    
    public void setProvisiones(Provisiones provisiones) {
        this.provisiones = provisiones;
    }
    public CausacionNomina getCausacionNomina() {
        return this.causacionNomina;
    }
    
    public void setCausacionNomina(CausacionNomina causacionNomina) {
        this.causacionNomina = causacionNomina;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


