package Entidades;
// Generated 19/12/2009 02:18:45 PM by Hibernate Tools 3.2.1.GA



/**
 * CausacionDeduccionNomina generated by hbm2java
 */
public class CausacionDeduccionNomina  implements java.io.Serializable {


     private int id;
     private int idCausacion;
     private int idDeduccion;

    public CausacionDeduccionNomina() {
    }

    public CausacionDeduccionNomina(int idCausacion, int idDeduccion) {
        this.idCausacion = idCausacion;
        this.idDeduccion = idDeduccion;
    }

    
    public CausacionDeduccionNomina(int id, int idCausacion, int idDeduccion) {
       this.id = id;
       this.idCausacion = idCausacion;
       this.idDeduccion = idDeduccion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public int getIdCausacion() {
        return this.idCausacion;
    }

    public void setIdCausacion(int idCausacion) {
        this.idCausacion = idCausacion;
    }
    public int getIdDeduccion() {
        return this.idDeduccion;
    }

    public void setIdDeduccion(int idDeduccion) {
        this.idDeduccion = idDeduccion;
    }

}


