package Entidades;
// Generated 16/02/2010 04:06:04 PM by Hibernate Tools 3.2.1.GA

import VO.ValorFijoPsVO;

/**
 * CausacionPs generated by hbm2java
 */
public class CausacionPs implements java.io.Serializable {

    private int id;
    private int idContrato;
    private int idFechaCorte;
    private double basico;
    private short diasTrabajados;
    private double totalDevengados;
    private double totalOtrosMas;
    private double total;
    private double totalRetenciones;
    private double totalDeducciones;
    private double totalAPagar;
    //NO HACEN PARTE DE LA TABLA
    private int[] idsDeducciones;
    private ProvisionPs[] provisionPses;
    private OtrosMasPs[] otrosMasPses;
    private ValorFijoPsVO[] valorFijoPsVOs;
    private String identificacion;
    private String rut;
    private String contratista;
    private double totalRetencionesBasicos;
    private double totalRetencionesOtros;

    public CausacionPs(double basico, short diasTrabajados, double totalDevengados, double totalOtrosMas, double total, double totalRetenciones, double totalDeducciones, double totalAPagar, int[] idsDeducciones, ProvisionPs[] provisionPses, OtrosMasPs[] otrosMasPses, ValorFijoPsVO[] valorFijoPsVOs, String identificacion, String rut, String contratista, double totalRetencionesBasicos, double totalRetencionesOtros,int idContrato) {
        this.idContrato = idContrato;
        this.basico = basico;
        this.diasTrabajados = diasTrabajados;
        this.totalDevengados = totalDevengados;
        this.totalOtrosMas = totalOtrosMas;
        this.total = total;
        this.totalRetenciones = totalRetenciones;
        this.totalDeducciones = totalDeducciones;
        this.totalAPagar = totalAPagar;
        this.idsDeducciones = idsDeducciones;
        this.provisionPses = provisionPses;
        this.otrosMasPses = otrosMasPses;
        this.valorFijoPsVOs = valorFijoPsVOs;
        this.identificacion = identificacion;
        this.rut = rut;
        this.contratista = contratista;
        this.totalRetencionesBasicos = totalRetencionesBasicos;
        this.totalRetencionesOtros = totalRetencionesOtros;
    }

    public CausacionPs(int idContrato,double basico, short diasTrabajados, double totalDevengados, double totalOtrosMas, double total, double totalRetenciones, double totalDeducciones, double totalAPagar, OtrosMasPs[] otrosMasPses, ValorFijoPsVO[] valorFijoPsVOs, String identificacion, String rut, String contratista, double totalRetencionesBasicos, double totalRetencionesOtros) {
        this.idContrato = idContrato;
        this.basico = basico;
        this.diasTrabajados = diasTrabajados;
        this.totalDevengados = totalDevengados;
        this.totalOtrosMas = totalOtrosMas;
        this.total = total;
        this.totalRetenciones = totalRetenciones;
        this.totalDeducciones = totalDeducciones;
        this.totalAPagar = totalAPagar;
        this.otrosMasPses = otrosMasPses;
        this.valorFijoPsVOs = valorFijoPsVOs;
        this.identificacion = identificacion;
        this.rut = rut;
        this.contratista = contratista;
        this.totalRetencionesBasicos = totalRetencionesBasicos;
        this.totalRetencionesOtros = totalRetencionesOtros;
    }

    public CausacionPs() {
    }

    public CausacionPs(int id, int idContrato, int idFechaCorte, double basico, short diasTrabajados, double totalDevengados, double totalOtrosMas, double total, double totalRetenciones, double totalDeducciones, double totalAPagar) {
        this.id = id;
        this.idContrato = idContrato;
        this.idFechaCorte = idFechaCorte;
        this.basico = basico;
        this.diasTrabajados = diasTrabajados;
        this.totalDevengados = totalDevengados;
        this.totalOtrosMas = totalOtrosMas;
        this.total = total;
        this.totalRetenciones = totalRetenciones;
        this.totalDeducciones = totalDeducciones;
        this.totalAPagar = totalAPagar;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdContrato() {
        return this.idContrato;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    public int getIdFechaCorte() {
        return this.idFechaCorte;
    }

    public void setIdFechaCorte(int idFechaCorte) {
        this.idFechaCorte = idFechaCorte;
    }

    public double getBasico() {
        return this.basico;
    }

    public void setBasico(double basico) {
        this.basico = basico;
    }

    public short getDiasTrabajados() {
        return this.diasTrabajados;
    }

    public void setDiasTrabajados(short diasTrabajados) {
        this.diasTrabajados = diasTrabajados;
    }

    public double getTotalDevengados() {
        return this.totalDevengados;
    }

    public void setTotalDevengados(double totalDevengados) {
        this.totalDevengados = totalDevengados;
    }

    public double getTotalOtrosMas() {
        return this.totalOtrosMas;
    }

    public void setTotalOtrosMas(double totalOtrosMas) {
        this.totalOtrosMas = totalOtrosMas;
    }

    public double getTotal() {
        return this.total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public double getTotalRetenciones() {
        return this.totalRetenciones;
    }

    public void setTotalRetenciones(double totalRetenciones) {
        this.totalRetenciones = totalRetenciones;
    }

    public double getTotalDeducciones() {
        return this.totalDeducciones;
    }

    public void setTotalDeducciones(double totalDeducciones) {
        this.totalDeducciones = totalDeducciones;
    }

    public double getTotalAPagar() {
        return this.totalAPagar;
    }

    public void setTotalAPagar(double totalAPagar) {
        this.totalAPagar = totalAPagar;
    }

    /**
     * @return the idsDeducciones
     */
    public int[] getIdsDeducciones() {
        return idsDeducciones;
    }

    /**
     * @param idsDeducciones the idsDeducciones to set
     */
    public void setIdsDeducciones(int[] idsDeducciones) {
        this.idsDeducciones = idsDeducciones;
    }

    /**
     * @return the provisionPses
     */
    public ProvisionPs[] getProvisionPses() {
        return provisionPses;
    }

    /**
     * @param provisionPses the provisionPses to set
     */
    public void setProvisionPses(ProvisionPs[] provisionPses) {
        this.provisionPses = provisionPses;
    }

    /**
     * @return the otrosMasPses
     */
    public OtrosMasPs[] getOtrosMasPses() {
        return otrosMasPses;
    }

    /**
     * @param otrosMasPses the otrosMasPses to set
     */
    public void setOtrosMasPses(OtrosMasPs[] otrosMasPses) {
        this.otrosMasPses = otrosMasPses;
    }

    /**
     * @return the valorFijoPsVOs
     */
    public ValorFijoPsVO[] getValorFijoPsVOs() {
        return valorFijoPsVOs;
    }

    /**
     * @param valorFijoPsVOs the valorFijoPsVOs to set
     */
    public void setValorFijoPsVOs(ValorFijoPsVO[] valorFijoPsVOs) {
        this.valorFijoPsVOs = valorFijoPsVOs;
    }

    /**
     * @return the identificacion
     */
    public String getIdentificacion() {
        return identificacion;
    }

    /**
     * @param identificacion the identificacion to set
     */
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    /**
     * @return the rut
     */
    public String getRut() {
        return rut;
    }

    /**
     * @param rut the rut to set
     */
    public void setRut(String rut) {
        this.rut = rut;
    }

    /**
     * @return the contratista
     */
    public String getContratista() {
        return contratista;
    }

    /**
     * @param contratista the contratista to set
     */
    public void setContratista(String contratista) {
        this.contratista = contratista;
    }

    /**
     * @return the totalRetencionesBasicos
     */
    public double getTotalRetencionesBasicos() {
        return totalRetencionesBasicos;
    }

    /**
     * @param totalRetencionesBasicos the totalRetencionesBasicos to set
     */
    public void setTotalRetencionesBasicos(double totalRetencionesBasicos) {
        this.totalRetencionesBasicos = totalRetencionesBasicos;
    }

    /**
     * @return the totalRetencionesOtros
     */
    public double getTotalRetencionesOtros() {
        return totalRetencionesOtros;
    }

    /**
     * @param totalRetencionesOtros the totalRetencionesOtros to set
     */
    public void setTotalRetencionesOtros(double totalRetencionesOtros) {
        this.totalRetencionesOtros = totalRetencionesOtros;
    }
}


