package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CentroDeCosto generated by hbm2java
 */
public class CentroDeCosto  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String ciudad;
     private Set movimientoses = new HashSet(0);
     private short esEmpresa;

    public CentroDeCosto() {
    }

    public CentroDeCosto(int id) {
        this.id = id;

    }

    public CentroDeCosto(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;

    }

    public CentroDeCosto(int id, String nombre, String ciudad) {
        this.id = id;
        this.nombre = nombre;
        this.ciudad = ciudad;
    }

    public CentroDeCosto(int id, String nombre, String ciudad,short esEmpresa) {
        this.id = id;
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.esEmpresa = esEmpresa;
    }
    public CentroDeCosto(int id, String nombre, String ciudad, Set movimientoses) {
       this.id = id;
       this.nombre = nombre;
       this.ciudad = ciudad;
       this.movimientoses = movimientoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }

    /**
     * @return the esEmpresa
     */
    public short getEsEmpresa() {
        return esEmpresa;
    }

    /**
     * @param esEmpresa the esEmpresa to set
     */
    public void setEsEmpresa(short esEmpresa) {
        this.esEmpresa = esEmpresa;
    }




}


