package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

    private int id;
    private Country country;
    private String name;
    private String district;
    private int population;
    private Set recursoHumanosForIdLugarExpedicion = new HashSet(0);
    private Set recursoHumanosForIdLugarNacimiento = new HashSet(0);

    public City(int id) {
        this.id = id;
    }

    public City(int id, String name) {
        this.id = id;
        this.name = name;

    }

    public City(int id, Country country, String name) {
        this.id = id;
        this.country = country;
        this.name = name;

    }

    public City() {
    }

    public City(int id, Country country, String name, String district, int population) {
        this.id = id;
        this.country = country;
        this.name = name;
        this.district = district;
        this.population = population;
    }

    public City(int id, Country country, String name, String district, int population, Set recursoHumanosForIdLugarExpedicion, Set recursoHumanosForIdLugarNacimiento) {
        this.id = id;
        this.country = country;
        this.name = name;
        this.district = district;
        this.population = population;
        this.recursoHumanosForIdLugarExpedicion = recursoHumanosForIdLugarExpedicion;
        this.recursoHumanosForIdLugarNacimiento = recursoHumanosForIdLugarNacimiento;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public int getPopulation() {
        return this.population;
    }

    public void setPopulation(int population) {
        this.population = population;
    }

    public Set getRecursoHumanosForIdLugarExpedicion() {
        return this.recursoHumanosForIdLugarExpedicion;
    }

    public void setRecursoHumanosForIdLugarExpedicion(Set recursoHumanosForIdLugarExpedicion) {
        this.recursoHumanosForIdLugarExpedicion = recursoHumanosForIdLugarExpedicion;
    }

    public Set getRecursoHumanosForIdLugarNacimiento() {
        return this.recursoHumanosForIdLugarNacimiento;
    }

    public void setRecursoHumanosForIdLugarNacimiento(Set recursoHumanosForIdLugarNacimiento) {
        this.recursoHumanosForIdLugarNacimiento = recursoHumanosForIdLugarNacimiento;
    }
}


