package Entidades;
// Generated 10/12/2009 12:00:43 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * CuentaCobroEstado generated by hbm2java
 */
public class CuentaCobroEstado implements java.io.Serializable {

    private int id;
    private int idCuentaCobro;
    private short idEstado;
    private Date fechaCambioEstado;
    private String nombreEstado;

    public CuentaCobroEstado() {
    }

    public CuentaCobroEstado(int id, int idCuentaCobro, short idEstado, Date fechaCambioEstado) {
        this.id = id;
        this.idCuentaCobro = idCuentaCobro;
        this.idEstado = idEstado;
        this.fechaCambioEstado = fechaCambioEstado;
    }

    public CuentaCobroEstado(int idCuentaCobro, short idEstado, Date fechaCambioEstado) {
        this.idCuentaCobro = idCuentaCobro;
        this.idEstado = idEstado;
        this.fechaCambioEstado = fechaCambioEstado;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdCuentaCobro() {
        return this.idCuentaCobro;
    }

    public void setIdCuentaCobro(int idCuentaCobro) {
        this.idCuentaCobro = idCuentaCobro;
    }

    public short getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(short idEstado) {
        this.idEstado = idEstado;
    }

    public Date getFechaCambioEstado() {
        return this.fechaCambioEstado;
    }

    public void setFechaCambioEstado(Date fechaCambioEstado) {
        this.fechaCambioEstado = fechaCambioEstado;
    }

    /**
     * @return the nombreEstado
     */
    public String getNombreEstado() {
        return nombreEstado;
    }

    /**
     * @param nombreEstado the nombreEstado to set
     */
    public void setNombreEstado(String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
}


