package Entidades;
// Generated 13/01/2010 04:55:30 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * CuentasPorPagar generated by hbm2java
 */
public class CuentasPorPagar implements java.io.Serializable {

    private int id;
    private Date fechaOrigen;
    private Integer idRecursoHumano;
    private Integer idPersona;
    private String concepto;
    private Integer idCuentaBancaria;
    private Integer idBanco;
    private Integer idTipoCuentaBanco;
    private String numeroCuenta;
    private Double valor;
    private Short idEstadoCuentaXPagar;
    private Short idGeneradorCuentaPago;
    private Integer idCampo;
    private Date fechaPago;
    

    public CuentasPorPagar(int id) {
        this.id = id;
    }
    
    public CuentasPorPagar(Date fechaOrigen, String concepto, Double valor, Short idEstadoCuentaXPagar, Short idGeneradorCuentaPago) {
        this.fechaOrigen = fechaOrigen;
        this.concepto = concepto;
        this.valor = valor;
        this.idEstadoCuentaXPagar = idEstadoCuentaXPagar;
        this.idGeneradorCuentaPago = idGeneradorCuentaPago;
        
    }

    
    public CuentasPorPagar(Date fechaOrigen, Integer idRecursoHumano, Integer idPersona, String concepto, Integer idCuentaBancaria, Integer idBanco, Integer idTipoCuentaBanco, String numeroCuenta, Double valor, Short idEstadoCuentaXPagar, Short idGeneradorCuentaPago, Integer idCampo, Date fechaPago) {
        this.fechaOrigen = fechaOrigen;
        this.idRecursoHumano = idRecursoHumano;
        this.idPersona = idPersona;
        this.concepto = concepto;
        this.idCuentaBancaria = idCuentaBancaria;
        this.idBanco = idBanco;
        this.idTipoCuentaBanco = idTipoCuentaBanco;
        this.numeroCuenta = numeroCuenta;
        this.valor = valor;
        this.idEstadoCuentaXPagar = idEstadoCuentaXPagar;
        this.idGeneradorCuentaPago = idGeneradorCuentaPago;
        this.idCampo = idCampo;
        this.fechaPago = fechaPago;
    }

    public CuentasPorPagar() {
    }

    public CuentasPorPagar(int id, Date fechaOrigen) {
        this.id = id;
        this.fechaOrigen = fechaOrigen;
    }

    public CuentasPorPagar(int id, Date fechaOrigen, Integer idRecursoHumano, Integer idPersona, String concepto, Integer idCuentaBancaria, Integer idBanco, Integer idTipoCuentaBanco, String numeroCuenta, Double valor, Short idEstadoCuentaXPagar, Short idGeneradorCuentaPago, Integer idCampo, Date fechaPago) {
        this.id = id;
        this.fechaOrigen = fechaOrigen;
        this.idRecursoHumano = idRecursoHumano;
        this.idPersona = idPersona;
        this.concepto = concepto;
        this.idCuentaBancaria = idCuentaBancaria;
        this.idBanco = idBanco;
        this.idTipoCuentaBanco = idTipoCuentaBanco;
        this.numeroCuenta = numeroCuenta;
        this.valor = valor;
        this.idEstadoCuentaXPagar = idEstadoCuentaXPagar;
        this.idGeneradorCuentaPago = idGeneradorCuentaPago;
        this.idCampo = idCampo;
        this.fechaPago = fechaPago;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getFechaOrigen() {
        return this.fechaOrigen;
    }

    public void setFechaOrigen(Date fechaOrigen) {
        this.fechaOrigen = fechaOrigen;
    }

    public Integer getIdRecursoHumano() {
        return this.idRecursoHumano;
    }

    public void setIdRecursoHumano(Integer idRecursoHumano) {
        this.idRecursoHumano = idRecursoHumano;
    }

    public Integer getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    public String getConcepto() {
        return this.concepto;
    }

    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public Integer getIdCuentaBancaria() {
        return this.idCuentaBancaria;
    }

    public void setIdCuentaBancaria(Integer idCuentaBancaria) {
        this.idCuentaBancaria = idCuentaBancaria;
    }

    public Integer getIdBanco() {
        return this.idBanco;
    }

    public void setIdBanco(Integer idBanco) {
        this.idBanco = idBanco;
    }

    public Integer getIdTipoCuentaBanco() {
        return this.idTipoCuentaBanco;
    }

    public void setIdTipoCuentaBanco(Integer idTipoCuentaBanco) {
        this.idTipoCuentaBanco = idTipoCuentaBanco;
    }

    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }

    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }

    public Double getValor() {
        return this.valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Short getIdEstadoCuentaXPagar() {
        return this.idEstadoCuentaXPagar;
    }

    public void setIdEstadoCuentaXPagar(Short idEstadoCuentaXPagar) {
        this.idEstadoCuentaXPagar = idEstadoCuentaXPagar;
    }

    public Short getIdGeneradorCuentaPago() {
        return this.idGeneradorCuentaPago;
    }

    public void setIdGeneradorCuentaPago(Short idGeneradorCuentaPago) {
        this.idGeneradorCuentaPago = idGeneradorCuentaPago;
    }

    public Integer getIdCampo() {
        return this.idCampo;
    }

    public void setIdCampo(Integer idCampo) {
        this.idCampo = idCampo;
    }

    public Date getFechaPago() {
        return this.fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
}


