package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA

/**
 * CuentaBancaria generated by hbm2java
 */
public class CuentaBancaria implements java.io.Serializable {

    private int id;
    private Banco banco;
    private TipoCuentaBancaria tipoCuentaBancaria;
    private RecursoHumano recursoHumano;
    private String numero;
    private short esActual;

    public CuentaBancaria() {
    }

    public CuentaBancaria(int id, Banco banco, TipoCuentaBancaria tipoCuentaBancaria, RecursoHumano recursoHumano, String numero, short esActual) {
        this.id = id;
        this.banco = banco;
        this.tipoCuentaBancaria = tipoCuentaBancaria;
        this.recursoHumano = recursoHumano;
        this.numero = numero;
        this.esActual = esActual;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Banco getBanco() {
        return this.banco;
    }

    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    public TipoCuentaBancaria getTipoCuentaBancaria() {
        return this.tipoCuentaBancaria;
    }

    public void setTipoCuentaBancaria(TipoCuentaBancaria tipoCuentaBancaria) {
        this.tipoCuentaBancaria = tipoCuentaBancaria;
    }

    public RecursoHumano getRecursoHumano() {
        return this.recursoHumano;
    }

    public void setRecursoHumano(RecursoHumano recursoHumano) {
        this.recursoHumano = recursoHumano;
    }

    public short getEsActual() {
        return this.esActual;
    }

    public void setEsActual(short esActual) {
        this.esActual = esActual;
    }

    /**
     * @return the numero
     */
    public String getNumero() {
        return numero;
    }

    /**
     * @param numero the numero to set
     */
    public void setNumero(String numero) {
        this.numero = numero;
    }
}


