package Entidades;
// Generated 22/10/2009 12:59:29 AM by Hibernate Tools 3.2.1.GA



/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private int id;
     private Factura factura;
     private String descripcionBienServicio;
     private short cantidad;
     private double precio;
     private double subtotal;
     private double total;

    public DetalleFactura() {
    }

    public DetalleFactura(Factura factura, String descripcionBienServicio, short cantidad, double precio, double subtotal, double total) {
       
       this.factura = factura;
       this.descripcionBienServicio = descripcionBienServicio;
       this.cantidad = cantidad;
       this.precio = precio;
       this.subtotal = subtotal;
       this.total = total;
    }

    public DetalleFactura(int id, Factura factura, String descripcionBienServicio, short cantidad, double precio, double subtotal, double total) {
       this.id = id;
       this.factura = factura;
       this.descripcionBienServicio = descripcionBienServicio;
       this.cantidad = cantidad;
       this.precio = precio;
       this.subtotal = subtotal;
       this.total = total;
    }

    public DetalleFactura(int idDetalleFactura) {
        this.id = idDetalleFactura;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getDescripcionBienServicio() {
        return this.descripcionBienServicio;
    }
    
    public void setDescripcionBienServicio(String descripcionBienServicio) {
        this.descripcionBienServicio = descripcionBienServicio;
    }
    public short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(short cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


