package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Eps generated by hbm2java
 */
public class Eps  implements java.io.Serializable {


     private int id;
     private String nombre;
     private short esEmpresa;
     private Set recursoHumanos = new HashSet(0);

    public Eps(int id) {
        this.id = id;
    }
    public Eps() {
    }

	
    public Eps(int id, String nombre, short esEmpresa) {
        this.id = id;
        this.nombre = nombre;
        this.esEmpresa = esEmpresa;
    }
    public Eps(int id, String nombre, short esEmpresa, Set recursoHumanos) {
       this.id = id;
       this.nombre = nombre;
       this.esEmpresa = esEmpresa;
       this.recursoHumanos = recursoHumanos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public short getEsEmpresa() {
        return this.esEmpresa;
    }
    
    public void setEsEmpresa(short esEmpresa) {
        this.esEmpresa = esEmpresa;
    }
    public Set getRecursoHumanos() {
        return this.recursoHumanos;
    }
    
    public void setRecursoHumanos(Set recursoHumanos) {
        this.recursoHumanos = recursoHumanos;
    }




}


