package Entidades;
// Generated 10/12/2009 12:02:40 PM by Hibernate Tools 3.2.1.GA



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private short id;
     private String nombre;

    public Estado() {
    }

    public Estado(short id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


