package Entidades;
// Generated 19/10/2009 12:36:38 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

    private int id;
    private Persona persona;
    private Date fechaFacturacion;
    private Date fechaPactadaPago;
    private double subtutal;
    private double total;
    private double saldo;
    private Set detalleFacturas = new HashSet(0);
    private Set abonos = new HashSet(0);
    private Set facturaIvas = new HashSet(0);
    private String numeroFactura;
    private String estadoFactura;

    public Factura() {
    }

    public Factura(int id) {
        this.id = id;
    }

    public Factura(Persona persona, Date fechaFacturacion, Date fechaPactadaPago) {
        this.persona = persona;
        this.fechaFacturacion = fechaFacturacion;
        this.fechaPactadaPago = fechaPactadaPago;
    }

    public Factura(Persona persona, Date fechaFacturacion, Date fechaPactadaPago, String numeroFactura,String estadoFactura) {
        this.persona = persona;
        this.fechaFacturacion = fechaFacturacion;
        this.fechaPactadaPago = fechaPactadaPago;
        this.numeroFactura = numeroFactura;
        this.estadoFactura = estadoFactura;
    }

    public Factura(int id, Persona persona, Date fechaFacturacion, Date fechaPactadaPago, double subtutal, double total, double saldo) {
        this.id = id;
        this.persona = persona;
        this.fechaFacturacion = fechaFacturacion;
        this.fechaPactadaPago = fechaPactadaPago;
        this.subtutal = subtutal;
        this.total = total;
        this.saldo = saldo;
    }

    public Factura(int id, Persona persona, Date fechaFacturacion, Date fechaPactadaPago, double subtutal, double total, double saldo, Set detalleFacturas, Set abonos, Set facturaIvas) {
        this.id = id;
        this.persona = persona;
        this.fechaFacturacion = fechaFacturacion;
        this.fechaPactadaPago = fechaPactadaPago;
        this.subtutal = subtutal;
        this.total = total;
        this.saldo = saldo;
        this.detalleFacturas = detalleFacturas;
        this.abonos = abonos;
        this.facturaIvas = facturaIvas;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Date getFechaFacturacion() {
        return this.fechaFacturacion;
    }

    public void setFechaFacturacion(Date fechaFacturacion) {
        this.fechaFacturacion = fechaFacturacion;
    }

    public Date getFechaPactadaPago() {
        return this.fechaPactadaPago;
    }

    public void setFechaPactadaPago(Date fechaPactadaPago) {
        this.fechaPactadaPago = fechaPactadaPago;
    }

    public double getSubtutal() {
        return this.subtutal;
    }

    public void setSubtutal(double subtutal) {
        this.subtutal = subtutal;
    }

    public double getTotal() {
        return this.total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public double getSaldo() {
        return this.saldo;
    }

    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }

    public Set getDetalleFacturas() {
        return this.detalleFacturas;
    }

    public void setDetalleFacturas(Set detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }

    public Set getAbonos() {
        return this.abonos;
    }

    public void setAbonos(Set abonos) {
        this.abonos = abonos;
    }

    public Set getFacturaIvas() {
        return this.facturaIvas;
    }

    public void setFacturaIvas(Set facturaIvas) {
        this.facturaIvas = facturaIvas;
    }

    /**
     * @return the numeroFactura
     */
    public String getNumeroFactura() {
        return numeroFactura;
    }

    /**
     * @param numeroFactura the numeroFactura to set
     */
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }

    /**
     * @return the estadoFactura
     */
    public String getEstadoFactura() {
        return estadoFactura;
    }

    /**
     * @param estadoFactura the estadoFactura to set
     */
    public void setEstadoFactura(String estadoFactura) {
        this.estadoFactura = estadoFactura;
    }
}


