package Entidades;
// Generated 19/10/2009 12:36:38 PM by Hibernate Tools 3.2.1.GA



/**
 * FacturaRetencion generated by hbm2java
 */
public class FacturaRetencion  implements java.io.Serializable {


     private int id;
     private Retenciones retenciones;
     private DetalleFactura detalleFactura;
     private double valor;

    public FacturaRetencion() {
    }

    public FacturaRetencion(int id, Retenciones retenciones, DetalleFactura detalleFactura, double valor) {
       this.id = id;
       this.retenciones = retenciones;
       this.detalleFactura = detalleFactura;
       this.valor = valor;
    }

     public FacturaRetencion(Retenciones retenciones, DetalleFactura detalleFactura, double valor) {
       
       this.retenciones = retenciones;
       this.detalleFactura = detalleFactura;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Retenciones getRetenciones() {
        return this.retenciones;
    }
    
    public void setRetenciones(Retenciones retenciones) {
        this.retenciones = retenciones;
    }
    public DetalleFactura getDetalleFactura() {
        return this.detalleFactura;
    }
    
    public void setDetalleFactura(DetalleFactura detalleFactura) {
        this.detalleFactura = detalleFactura;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


