package Entidades;
// Generated 4/11/2009 10:54:35 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * FechasPago generated by hbm2java
 */
public class FechasPago implements java.io.Serializable {

    private int id;
    private ValorFormaPago valorFormaPago;
    private Date fecha;
    private Date iniPeriodoPago;
    private Date finPeriodoPago;
    private short idTipoContrato;
    private short pagada;
    private short activa;
    private String estado;
    
   

    public FechasPago(ValorFormaPago valorFormaPago, Date fecha, Date iniPeriodoPago, Date finPeriodoPago, short idTipoContrato, short pagada) {
        this.valorFormaPago = valorFormaPago;
        this.fecha = fecha;
        this.iniPeriodoPago = iniPeriodoPago;
        this.finPeriodoPago = finPeriodoPago;
        this.idTipoContrato = idTipoContrato;
        this.pagada = pagada;
    }

    public FechasPago(int id, Date fecha,
            Date iniPeriodoPago,
            Date finPeriodoPago, short pagada, short idTipoContrato) {
        this.id = id;
        this.fecha = fecha;
        this.iniPeriodoPago = iniPeriodoPago;
        this.finPeriodoPago = finPeriodoPago;
        this.pagada = pagada;
        this.idTipoContrato = idTipoContrato;
    }

    public FechasPago(Date fecha,
            Date iniPeriodoPago,
            Date finPeriodoPago) {
        this.fecha = fecha;
        this.iniPeriodoPago = iniPeriodoPago;
        this.finPeriodoPago = finPeriodoPago;
    }

    public FechasPago(int id) {
        this.id = id;
    }

    public FechasPago() {
    }

    public FechasPago(int id, ValorFormaPago valorFormaPago, Date fecha) {
        this.id = id;
        this.valorFormaPago = valorFormaPago;
        this.fecha = fecha;
    }

    public FechasPago(ValorFormaPago valorFormaPago, Date fecha) {

        this.valorFormaPago = valorFormaPago;
        this.fecha = fecha;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public ValorFormaPago getValorFormaPago() {
        return this.valorFormaPago;
    }

    public void setValorFormaPago(ValorFormaPago valorFormaPago) {
        this.valorFormaPago = valorFormaPago;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * @return the iniPeriodoPago
     */
    public Date getIniPeriodoPago() {
        return iniPeriodoPago;
    }

    /**
     * @param iniPeriodoPago the iniPeriodoPago to set
     */
    public void setIniPeriodoPago(Date iniPeriodoPago) {
        this.iniPeriodoPago = iniPeriodoPago;
    }

    /**
     * @return the finPeriodoPago
     */
    public Date getFinPeriodoPago() {
        return finPeriodoPago;
    }

    /**
     * @param finPeriodoPago the finPeriodoPago to set
     */
    public void setFinPeriodoPago(Date finPeriodoPago) {
        this.finPeriodoPago = finPeriodoPago;
    }

    /**
     * @return the idTipoContrato
     */
    public short getIdTipoContrato() {
        return idTipoContrato;
    }

    /**
     * @param idTipoContrato the idTipoContrato to set
     */
    public void setIdTipoContrato(short idTipoContrato) {
        this.idTipoContrato = idTipoContrato;
    }

    /**
     * @return the pagada
     */
    public short getPagada() {
        return pagada;
    }

    /**
     * @param pagada the pagada to set
     */
    public void setPagada(short pagada) {
        this.pagada = pagada;
    }

    /**
     * @return the estado
     */
    public String getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * @return the activa
     */
    public short getActiva() {
        return activa;
    }

    /**
     * @param activa the activa to set
     */
    public void setActiva(short activa) {
        this.activa = activa;
    }
}


