package Entidades;
// Generated 9/11/2009 09:25:53 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * FechasCorteCausacion generated by hbm2java
 */
public class FechasCorteCausacion implements java.io.Serializable {

    private int id;
    private Date fechaCorte;
    private short tipoCausacion;
    private int mesCausado;
    private int yearCausado;


    public FechasCorteCausacion(Date fechaCorte, short tipoCausacion, int mesCausado, int yearCausado) {
        this.fechaCorte = fechaCorte;
        this.tipoCausacion = tipoCausacion;
        this.mesCausado = mesCausado;
        this.yearCausado = yearCausado;
    }

    public FechasCorteCausacion(int id) {
        this.id = id;
    }

    
    public FechasCorteCausacion() {
    }

    public FechasCorteCausacion(int id, Date fechaCorte, short tipoCausacion, int mesCausado, int yearCausado) {
        this.id = id;
        this.fechaCorte = fechaCorte;
        this.tipoCausacion = tipoCausacion;
        this.mesCausado = mesCausado;
        this.yearCausado = yearCausado;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getFechaCorte() {
        return this.fechaCorte;
    }

    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }

    public short getTipoCausacion() {
        return this.tipoCausacion;
    }

    public void setTipoCausacion(short tipoCausacion) {
        this.tipoCausacion = tipoCausacion;
    }

    public int getMesCausado() {
        return this.mesCausado;
    }

    public void setMesCausado(int mesCausado) {
        this.mesCausado = mesCausado;
    }

    public int getYearCausado() {
        return this.yearCausado;
    }

    public void setYearCausado(int yearCausado) {
        this.yearCausado = yearCausado;
    }
}


