package Entidades;
// Generated 6/12/2009 05:30:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Formula generated by hbm2java
 */
public class Formula  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Date fecha;
     private String formula;
     private int idTipoFormula;

    public Formula() {
    }

    public Formula(int id, String nombre, String descripcion, Date fecha, String formula, int idTipoFormula) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.formula = formula;
       this.idTipoFormula = idTipoFormula;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    public int getIdTipoFormula() {
        return this.idTipoFormula;
    }
    
    public void setIdTipoFormula(int idTipoFormula) {
        this.idTipoFormula = idTipoFormula;
    }




}


