package Entidades;
// Generated 6/12/2009 05:20:34 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Liquidacion generated by hbm2java
 */
public class Liquidacion implements java.io.Serializable {

    private int id;
    private int idContrato;
    private int idCuentaBancaria;
    private int idFormulaPs;
    private int idFormulaVacaciones;
    private int idFormulaCesantias;
    private int idFormuInteresCesan;
    private int diasTrabajados;
    private double primaServicios;
    private double vacaciones;
    private double cesantias;
    private double interesesCesantias;
    private double totalLiquidacion;
    private Date fechaLiquidacion;
    private Date fechaPago;
    private double sueldoBasico;
    private String cuentaBancaria = "";
    private String formulaPs = "";
    private String formulaVacaciones = "";
    private String formulaCesantias = "";
    private String formuInteresCesan = "";
    
    public Liquidacion() {
    }

    public Liquidacion(int id) {
        this.id = id;
    }

    public Liquidacion(double primaServicios, double vacaciones, double cesantias, double interesesCesantias, double totalLiquidacion) {
        this.primaServicios = primaServicios;
        this.vacaciones = vacaciones;
        this.cesantias = cesantias;
        this.interesesCesantias = interesesCesantias;
        this.totalLiquidacion = totalLiquidacion;
    }

    public Liquidacion(int id, int idContrato, int idCuentaBancaria, int idFormulaPs, int idFormulaVacaciones, int idFormulaCesantias, int idFormuInteresCesan, int diasTrabajados, double primaServicios, double vacaciones, double cesantias, double interesesCesantias, double totalLiquidacion, Date fechaLiquidacion) {
        this.id = id;
        this.idContrato = idContrato;
        this.idCuentaBancaria = idCuentaBancaria;
        this.idFormulaPs = idFormulaPs;
        this.idFormulaVacaciones = idFormulaVacaciones;
        this.idFormulaCesantias = idFormulaCesantias;
        this.idFormuInteresCesan = idFormuInteresCesan;
        this.diasTrabajados = diasTrabajados;
        this.primaServicios = primaServicios;
        this.vacaciones = vacaciones;
        this.cesantias = cesantias;
        this.interesesCesantias = interesesCesantias;
        this.totalLiquidacion = totalLiquidacion;
        this.fechaLiquidacion = fechaLiquidacion;
    }

    public Liquidacion(int id, int idContrato, int idCuentaBancaria, int idFormulaPs, int idFormulaVacaciones, int idFormulaCesantias, int idFormuInteresCesan, int diasTrabajados, double primaServicios, double vacaciones, double cesantias, double interesesCesantias, double totalLiquidacion, Date fechaLiquidacion, Date fechaPago) {
        this.id = id;
        this.idContrato = idContrato;
        this.idCuentaBancaria = idCuentaBancaria;
        this.idFormulaPs = idFormulaPs;
        this.idFormulaVacaciones = idFormulaVacaciones;
        this.idFormulaCesantias = idFormulaCesantias;
        this.idFormuInteresCesan = idFormuInteresCesan;
        this.diasTrabajados = diasTrabajados;
        this.primaServicios = primaServicios;
        this.vacaciones = vacaciones;
        this.cesantias = cesantias;
        this.interesesCesantias = interesesCesantias;
        this.totalLiquidacion = totalLiquidacion;
        this.fechaLiquidacion = fechaLiquidacion;
        this.fechaPago = fechaPago;
    }

    public Liquidacion(int idContrato, int idCuentaBancaria, int idFormulaPs, int idFormulaVacaciones, int idFormulaCesantias, int idFormuInteresCesan, int diasTrabajados, double primaServicios, double vacaciones, double cesantias, double interesesCesantias, double totalLiquidacion, Date fechaLiquidacion, Date fechaPago) {
        this.idContrato = idContrato;
        this.idCuentaBancaria = idCuentaBancaria;
        this.idFormulaPs = idFormulaPs;
        this.idFormulaVacaciones = idFormulaVacaciones;
        this.idFormulaCesantias = idFormulaCesantias;
        this.idFormuInteresCesan = idFormuInteresCesan;
        this.diasTrabajados = diasTrabajados;
        this.primaServicios = primaServicios;
        this.vacaciones = vacaciones;
        this.cesantias = cesantias;
        this.interesesCesantias = interesesCesantias;
        this.totalLiquidacion = totalLiquidacion;
        this.fechaLiquidacion = fechaLiquidacion;
        this.fechaPago = fechaPago;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdContrato() {
        return this.idContrato;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    public int getIdCuentaBancaria() {
        return this.idCuentaBancaria;
    }

    public void setIdCuentaBancaria(int idCuentaBancaria) {
        this.idCuentaBancaria = idCuentaBancaria;
    }

    public int getIdFormulaPs() {
        return this.idFormulaPs;
    }

    public void setIdFormulaPs(int idFormulaPs) {
        this.idFormulaPs = idFormulaPs;
    }

    public int getIdFormulaVacaciones() {
        return this.idFormulaVacaciones;
    }

    public void setIdFormulaVacaciones(int idFormulaVacaciones) {
        this.idFormulaVacaciones = idFormulaVacaciones;
    }

    public int getIdFormulaCesantias() {
        return this.idFormulaCesantias;
    }

    public void setIdFormulaCesantias(int idFormulaCesantias) {
        this.idFormulaCesantias = idFormulaCesantias;
    }

    public int getIdFormuInteresCesan() {
        return this.idFormuInteresCesan;
    }

    public void setIdFormuInteresCesan(int idFormuInteresCesan) {
        this.idFormuInteresCesan = idFormuInteresCesan;
    }

    public int getDiasTrabajados() {
        return this.diasTrabajados;
    }

    public void setDiasTrabajados(int diasTrabajados) {
        this.diasTrabajados = diasTrabajados;
    }

    public double getPrimaServicios() {
        return this.primaServicios;
    }

    public void setPrimaServicios(double primaServicios) {
        this.primaServicios = primaServicios;
    }

    public double getVacaciones() {
        return this.vacaciones;
    }

    public void setVacaciones(double vacaciones) {
        this.vacaciones = vacaciones;
    }

    public double getCesantias() {
        return this.cesantias;
    }

    public void setCesantias(double cesantias) {
        this.cesantias = cesantias;
    }

    public double getInteresesCesantias() {
        return this.interesesCesantias;
    }

    public void setInteresesCesantias(double interesesCesantias) {
        this.interesesCesantias = interesesCesantias;
    }

    public double getTotalLiquidacion() {
        return this.totalLiquidacion;
    }

    public void setTotalLiquidacion(double totalLiquidacion) {
        this.totalLiquidacion = totalLiquidacion;
    }

    public Date getFechaLiquidacion() {
        return this.fechaLiquidacion;
    }

    public void setFechaLiquidacion(Date fechaLiquidacion) {
        this.fechaLiquidacion = fechaLiquidacion;
    }

    public Date getFechaPago() {
        return this.fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    /**
     * @return the sueldoBasico
     */
    public double getSueldoBasico() {
        return sueldoBasico;
    }

    /**
     * @param sueldoBasico the sueldoBasico to set
     */
    public void setSueldoBasico(double sueldoBasico) {
        this.sueldoBasico = sueldoBasico;
    }

    /**
     * @return the cuentaBancaria
     */
    public String getCuentaBancaria() {
        return cuentaBancaria;
    }

    /**
     * @param cuentaBancaria the cuentaBancaria to set
     */
    public void setCuentaBancaria(String cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }

    /**
     * @return the formulaPs
     */
    public String getFormulaPs() {
        return formulaPs;
    }

    /**
     * @param formulaPs the formulaPs to set
     */
    public void setFormulaPs(String formulaPs) {
        this.formulaPs = formulaPs;
    }

    /**
     * @return the formulaVacaciones
     */
    public String getFormulaVacaciones() {
        return formulaVacaciones;
    }

    /**
     * @param formulaVacaciones the formulaVacaciones to set
     */
    public void setFormulaVacaciones(String formulaVacaciones) {
        this.formulaVacaciones = formulaVacaciones;
    }

    /**
     * @return the formulaCesantias
     */
    public String getFormulaCesantias() {
        return formulaCesantias;
    }

    /**
     * @param formulaCesantias the formulaCesantias to set
     */
    public void setFormulaCesantias(String formulaCesantias) {
        this.formulaCesantias = formulaCesantias;
    }

    /**
     * @return the formuInteresCesan
     */
    public String getFormuInteresCesan() {
        return formuInteresCesan;
    }

    /**
     * @param formuInteresCesan the formuInteresCesan to set
     */
    public void setFormuInteresCesan(String formuInteresCesan) {
        this.formuInteresCesan = formuInteresCesan;
    }
}


