package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private int id;
     private TipoMovimiento tipoMovimiento;
     private Persona persona;
     private CajaMenor cajaMenor;
     private CentroDeCosto centroDeCosto;
     private XmlEstractoBanco xmlEstractoBanco;
     private double valor;
     private Date fechaMovimiento;
     private int idUsuario;
     private String concepto;
     private short isApertura;
     private Set soportes = new HashSet(0);
    

    public Movimientos() {
    }

    public Movimientos(int id) {
        this.id = id;
    }
	
    public Movimientos(int id, TipoMovimiento tipoMovimiento, Persona persona, CentroDeCosto centroDeCosto, double valor, Date fechaMovimiento, int idUsuario, short isApertura) {
        this.id = id;
        this.tipoMovimiento = tipoMovimiento;
        this.persona = persona;
        this.centroDeCosto = centroDeCosto;
        this.valor = valor;
        this.fechaMovimiento = fechaMovimiento;
        this.idUsuario = idUsuario;
        this.isApertura = isApertura;
    }

   public Movimientos(int id, TipoMovimiento tipoMovimiento, Persona persona, CajaMenor cajaMenor, CentroDeCosto centroDeCosto, XmlEstractoBanco xmlEstractoBanco, double valor, Date fechaMovimiento, int idUsuario, String concepto, short isApertura, Set soportes) {
       this.id = id;
       this.tipoMovimiento = tipoMovimiento;
       this.persona = persona;
       this.cajaMenor = cajaMenor;
       this.centroDeCosto = centroDeCosto;
       this.xmlEstractoBanco = xmlEstractoBanco;
       this.valor = valor;
       this.fechaMovimiento = fechaMovimiento;
       this.idUsuario = idUsuario;
       this.concepto = concepto;
       this.isApertura = isApertura;
       this.soportes = soportes;
    }
   //mio
    public Movimientos(int id, TipoMovimiento tipoMovimiento, Persona persona, CajaMenor cajaMenor, CentroDeCosto centroDeCosto,double valor, Date fechaMovimiento, int idUsuario, String concepto, short isApertura) {
       this.id = id;
       this.tipoMovimiento = tipoMovimiento;
       this.persona = persona;
       this.cajaMenor = cajaMenor;
       this.centroDeCosto = centroDeCosto;
   
       this.valor = valor;
       this.fechaMovimiento = fechaMovimiento;
       this.idUsuario = idUsuario;
       this.concepto = concepto;
       this.isApertura = isApertura;
   
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoMovimiento getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public CajaMenor getCajaMenor() {
        return this.cajaMenor;
    }
    
    public void setCajaMenor(CajaMenor cajaMenor) {
        this.cajaMenor = cajaMenor;
    }
    public CentroDeCosto getCentroDeCosto() {
        return this.centroDeCosto;
    }
    
    public void setCentroDeCosto(CentroDeCosto centroDeCosto) {
        this.centroDeCosto = centroDeCosto;
    }
    public XmlEstractoBanco getXmlEstractoBanco() {
        return this.xmlEstractoBanco;
    }
    
    public void setXmlEstractoBanco(XmlEstractoBanco xmlEstractoBanco) {
        this.xmlEstractoBanco = xmlEstractoBanco;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getFechaMovimiento() {
        return this.fechaMovimiento;
    }
    
    public void setFechaMovimiento(Date fechaMovimiento) {
        this.fechaMovimiento = fechaMovimiento;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public short getIsApertura() {
        return this.isApertura;
    }
    
    public void setIsApertura(short isApertura) {
        this.isApertura = isApertura;
    }
    public Set getSoportes() {
        return this.soportes;
    }
    
    public void setSoportes(Set soportes) {
        this.soportes = soportes;
    }




}


