package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA



/**
 * NotificacionCajaMenor generated by hbm2java
 */
public class NotificacionCajaMenor  implements java.io.Serializable {


     private int id;
     private UsuarioSys usuarioSys;
     private CajaMenor cajaMenor;
     private short esResponsable;

    public NotificacionCajaMenor() {
    }

    public NotificacionCajaMenor(int id, UsuarioSys usuarioSys, CajaMenor cajaMenor, short esResponsable) {
       this.id = id;
       this.usuarioSys = usuarioSys;
       this.cajaMenor = cajaMenor;
       this.esResponsable = esResponsable;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public UsuarioSys getUsuarioSys() {
        return this.usuarioSys;
    }
    
    public void setUsuarioSys(UsuarioSys usuarioSys) {
        this.usuarioSys = usuarioSys;
    }
    public CajaMenor getCajaMenor() {
        return this.cajaMenor;
    }
    
    public void setCajaMenor(CajaMenor cajaMenor) {
        this.cajaMenor = cajaMenor;
    }
    public short getEsResponsable() {
        return this.esResponsable;
    }
    
    public void setEsResponsable(short esResponsable) {
        this.esResponsable = esResponsable;
    }




}


