package Entidades;
// Generated 26/10/2009 03:30:08 PM by Hibernate Tools 3.2.1.GA



/**
 * OficioDesempenar generated by hbm2java
 */
public class OficioDesempenar  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String objeto;

    public OficioDesempenar(int id) {
       this.id = id;
       
    }

    public OficioDesempenar() {
    }

    public OficioDesempenar(int id, String nombre, String objeto) {
       this.id = id;
       this.nombre = nombre;
       this.objeto = objeto;
    }
    public OficioDesempenar(String nombre, String objeto) {
       
       this.nombre = nombre;
       this.objeto = objeto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(String objeto) {
        this.objeto = objeto;
    }




}


