package Entidades;
// Generated 16/02/2010 03:41:51 PM by Hibernate Tools 3.2.1.GA

/**
 * OtrosMasPs generated by hbm2java
 */
public class OtrosMasPs implements java.io.Serializable {

    private int id;
    private String nombre;
    private String observacion;
    private double valor;
    private double porcentaje;
    private double valorRetencion;
    private double total;
    private int idCausacionPs;

    public OtrosMasPs() {
    }

    public OtrosMasPs(int id, String nombre, String observacion, double valor, double porcentaje, double valorRetencion, double total, int idCausacionPs) {
        this.id = id;
        this.nombre = nombre;
        this.observacion = observacion;
        this.valor = valor;
        this.porcentaje = porcentaje;
        this.valorRetencion = valorRetencion;
        this.total = total;
        this.idCausacionPs = idCausacionPs;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public double getPorcentaje() {
        return this.porcentaje;
    }

    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }

    public double getValorRetencion() {
        return this.valorRetencion;
    }

    public void setValorRetencion(double valorRetencion) {
        this.valorRetencion = valorRetencion;
    }

    public double getTotal() {
        return this.total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public int getIdCausacionPs() {
        return this.idCausacionPs;
    }

    public void setIdCausacionPs(int idCausacionPs) {
        this.idCausacionPs = idCausacionPs;
    }
}


