package Entidades;
// Generated 19/02/2010 12:16:30 AM by Hibernate Tools 3.2.1.GA

/**
 * OtroMasNomina generated by hbm2java
 */
public class OtroMasNomina implements java.io.Serializable {

    private int id;
    private String nombre;
    private String observacion;
    private double valor;
    private short afectaIbc;
    private int idCausacionNomina;
    //NO SON DE LA TABLA
    private String strAfectaIbc;
    private boolean seleccionado;

    public OtroMasNomina(String nombre, String observacion, double valor, short afectaIbc, int idCausacionNomina) {
        this.nombre = nombre;
        this.observacion = observacion;
        this.valor = valor;
        this.afectaIbc = afectaIbc;
        this.idCausacionNomina = idCausacionNomina;
    }

    //nombre, observacion, valor, afectaIbc, idCausacion



    public OtroMasNomina(int id) {
        this.id = id;
    }

    public OtroMasNomina() {
    }

    public OtroMasNomina(int id, String nombre, String observacion, double valor, short afectaIbc, int idCausacionNomina) {
        this.id = id;
        this.nombre = nombre;
        this.observacion = observacion;
        this.valor = valor;
        this.afectaIbc = afectaIbc;
        this.idCausacionNomina = idCausacionNomina;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public double getValor() {
        return this.valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public short getAfectaIbc() {
        return this.afectaIbc;
    }

    public void setAfectaIbc(short afectaIbc) {
        this.afectaIbc = afectaIbc;
    }

    public int getIdCausacionNomina() {
        return this.idCausacionNomina;
    }

    public void setIdCausacionNomina(int idCausacionNomina) {
        this.idCausacionNomina = idCausacionNomina;
    }

    /**
     * @return the strAfectaIbc
     */
    public String getStrAfectaIbc() {
        return strAfectaIbc;
    }

    /**
     * @param strAfectaIbc the strAfectaIbc to set
     */
    public void setStrAfectaIbc(String strAfectaIbc) {
        this.strAfectaIbc = strAfectaIbc;
    }

    /**
     * @return the seleccionado
     */
    public boolean isSeleccionado() {
        return seleccionado;
    }

    /**
     * @param seleccionado the seleccionado to set
     */
    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }
}


