package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

    private short id;
    private String nombre;
    private Set rolPermisoses = new HashSet(0);

    public Permisos() {
    }

    public Permisos(short id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Permisos(short id) {
        this.id = id;

    }

    public Permisos(short id, String nombre, Set rolPermisoses) {
        this.id = id;
        this.nombre = nombre;
        this.rolPermisoses = rolPermisoses;
    }

    public short getId() {
        return this.id;
    }

    public void setId(short id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getRolPermisoses() {
        return this.rolPermisoses;
    }

    public void setRolPermisoses(Set rolPermisoses) {
        this.rolPermisoses = rolPermisoses;
    }
}


