package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    private int id;
    private BigDecimal nit;
    private Integer cedula;
    private Integer telefono;
    private String nombreRs;
    private Set movimientoses = new HashSet(0);
    private short esEmpresa;
    private short esUsuario;
    private String cual;
    private String numeroCual;

    public Persona() {
    }

    public Persona(int id) {
        this.id = id;
    }

    public Persona(int id, String nombreRs) {
        this.id = id;
        this.nombreRs = nombreRs;
    }

    public Persona(int id, String nombreRs, short esEmpresa) {
        this.id = id;
        this.nombreRs = nombreRs;
        this.esEmpresa = esEmpresa;
    }

    public Persona(int id, BigDecimal nit, Integer cedula, Integer telefono, String nombreRs, Set movimientoses) {
        this.id = id;
        this.nit = nit;
        this.cedula = cedula;
        this.telefono = telefono;
        this.nombreRs = nombreRs;
        this.movimientoses = movimientoses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public BigDecimal getNit() {
        return this.nit;
    }

    public void setNit(BigDecimal nit) {
        this.nit = nit;
    }

    public Integer getCedula() {
        return this.cedula;
    }

    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }

    public Integer getTelefono() {
        return this.telefono;
    }

    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    public String getNombreRs() {
        return this.nombreRs;
    }

    public void setNombreRs(String nombreRs) {
        this.nombreRs = nombreRs;
    }

    public Set getMovimientoses() {
        return this.movimientoses;
    }

    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }

    /**
     * @return the esEmpresa
     */
    public short getEsEmpresa() {
        return esEmpresa;
    }

    /**
     * @param esEmpresa the esEmpresa to set
     */
    public void setEsEmpresa(short esEmpresa) {
        this.esEmpresa = esEmpresa;
    }

    /**
     * @return the esUsuario
     */
    public short getEsUsuario() {
        return esUsuario;
    }

    /**
     * @param esUsuario the esUsuario to set
     */
    public void setEsUsuario(short esUsuario) {
        this.esUsuario = esUsuario;
    }

    /**
     * @return the cual
     */
    public String getCual() {
        return cual;
    }

    /**
     * @param cual the cual to set
     */
    public void setCual(String cual) {
        this.cual = cual;
    }

    /**
     * @return the numeroCual
     */
    public String getNumeroCual() {
        return numeroCual;
    }

    /**
     * @param numeroCual the numeroCual to set
     */
    public void setNumeroCual(String numeroCual) {
        this.numeroCual = numeroCual;
    }
}


