package Entidades;
// Generated 16/02/2010 03:14:20 PM by Hibernate Tools 3.2.1.GA



/**
 * ProvisionPs generated by hbm2java
 */
public class ProvisionPs  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double valor;
     private String observacion;
     private int idCausacionPs;

    public ProvisionPs() {
    }

    public ProvisionPs(int id, String nombre, double valor, String observacion, int idCausacionPs) {
       this.id = id;
       this.nombre = nombre;
       this.valor = valor;
       this.observacion = observacion;
       this.idCausacionPs = idCausacionPs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getIdCausacionPs() {
        return this.idCausacionPs;
    }
    
    public void setIdCausacionPs(int idCausacionPs) {
        this.idCausacionPs = idCausacionPs;
    }




}


