package Entidades;
// Generated 9/11/2009 07:01:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Provisiones generated by hbm2java
 */
public class Provisiones  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String observacion;
     private boolean seleccionado;
     private double valor;

    public Provisiones() {
    }

    public Provisiones(int id) {
        this.id = id;
        //this.nombre = nombre;
    }
	
    public Provisiones(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Provisiones(int id, String nombre, String observacion) {
       this.id = id;
       this.nombre = nombre;
       this.observacion = observacion;

    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    /**
     * @return the seleccionado
     */
    public boolean isSeleccionado() {
        return seleccionado;
    }

    /**
     * @param seleccionado the seleccionado to set
     */
    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }

    /**
     * @return the valor
     */
    public double getValor() {
        return valor;
    }

    /**
     * @param valor the valor to set
     */
    public void setValor(double valor) {
        this.valor = valor;
    }




}


