package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA

import VO.CuentaBancariaVO;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * RecursoHumano generated by hbm2java
 */
public class RecursoHumano implements java.io.Serializable {

    private int id;
    private City cityByIdLugarNacimiento;
    private City cityByIdLugarExpedicion;
    private Arp arp;
    private Afp afp;
    private Eps eps;
    private String nombre;
    private String apellido;
    private int cedula;
    private String correoElectronico;
    private String telefono;
    private String direccionDomicilio;
    private String celular;
    private Date fechaNacimiento;
    private String rut;
    private short presentoRut;
    private short presentoCedula;
    private short presntoHv;
    private short presentoEntrevista;
    private String login;
    private String contrasena;
    private Set cuentaBancarias = new HashSet(0);
    //No pertecen a la entidad
    private List<Contrato> contratos;
    private List<CuentaBancariaVO> cuentaBancariaVOs;


    public RecursoHumano(String nombre, String apellido, int cedula, String correoElectronico, String telefono, String direccionDomicilio, String celular, Date fechaNacimiento, String rut, short presentoRut, short presentoCedula, short presntoHv, short presentoEntrevista) {

        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.correoElectronico = correoElectronico;
        this.telefono = telefono;
        this.direccionDomicilio = direccionDomicilio;
        this.celular = celular;
        this.fechaNacimiento = fechaNacimiento;
        this.rut = rut;
        this.presentoRut = presentoRut;
        this.presentoCedula = presentoCedula;
        this.presntoHv = presntoHv;
        this.presentoEntrevista = presentoEntrevista;
    }

    public RecursoHumano(int id) {
        this.id = id;
    }

    public RecursoHumano() {
    }

    public RecursoHumano(int id, City cityByIdLugarNacimiento, City cityByIdLugarExpedicion, String nombre, String apellido, int cedula, String correoElectronico, String telefono, String direccionDomicilio, String celular, Date fechaNacimiento, String rut, short presentoRut, short presentoCedula, short presntoHv, short presentoEntrevista) {
        this.id = id;
        this.cityByIdLugarNacimiento = cityByIdLugarNacimiento;
        this.cityByIdLugarExpedicion = cityByIdLugarExpedicion;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.correoElectronico = correoElectronico;
        this.telefono = telefono;
        this.direccionDomicilio = direccionDomicilio;
        this.celular = celular;
        this.fechaNacimiento = fechaNacimiento;
        this.rut = rut;
        this.presentoRut = presentoRut;
        this.presentoCedula = presentoCedula;
        this.presntoHv = presntoHv;
        this.presentoEntrevista = presentoEntrevista;
    }

    public RecursoHumano(int id, City cityByIdLugarNacimiento, City cityByIdLugarExpedicion, Arp arp, Afp afp, Eps eps, String nombre, String apellido, int cedula, String correoElectronico, String telefono, String direccionDomicilio, String celular, Date fechaNacimiento, String rut, short presentoRut, short presentoCedula, short presntoHv, short presentoEntrevista, Set cuentaBancarias) {
        this.id = id;
        this.cityByIdLugarNacimiento = cityByIdLugarNacimiento;
        this.cityByIdLugarExpedicion = cityByIdLugarExpedicion;
        this.arp = arp;
        this.afp = afp;
        this.eps = eps;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.correoElectronico = correoElectronico;
        this.telefono = telefono;
        this.direccionDomicilio = direccionDomicilio;
        this.celular = celular;
        this.fechaNacimiento = fechaNacimiento;
        this.rut = rut;
        this.presentoRut = presentoRut;
        this.presentoCedula = presentoCedula;
        this.presntoHv = presntoHv;
        this.presentoEntrevista = presentoEntrevista;
        this.cuentaBancarias = cuentaBancarias;
    }

    public RecursoHumano(int id, String nombreApellido, int cedula) {
        this.id = id;
        this.nombre = nombreApellido;
        this.cedula = cedula;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public City getCityByIdLugarNacimiento() {
        return this.cityByIdLugarNacimiento;
    }

    public void setCityByIdLugarNacimiento(City cityByIdLugarNacimiento) {
        this.cityByIdLugarNacimiento = cityByIdLugarNacimiento;
    }

    public City getCityByIdLugarExpedicion() {
        return this.cityByIdLugarExpedicion;
    }

    public void setCityByIdLugarExpedicion(City cityByIdLugarExpedicion) {
        this.cityByIdLugarExpedicion = cityByIdLugarExpedicion;
    }

    public Arp getArp() {
        return this.arp;
    }

    public void setArp(Arp arp) {
        this.arp = arp;
    }

    public Afp getAfp() {
        return this.afp;
    }

    public void setAfp(Afp afp) {
        this.afp = afp;
    }

    public Eps getEps() {
        return this.eps;
    }

    public void setEps(Eps eps) {
        this.eps = eps;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public int getCedula() {
        return this.cedula;
    }

    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    public String getCorreoElectronico() {
        return this.correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getDireccionDomicilio() {
        return this.direccionDomicilio;
    }

    public void setDireccionDomicilio(String direccionDomicilio) {
        this.direccionDomicilio = direccionDomicilio;
    }

    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getRut() {
        return this.rut;
    }

    public void setRut(String rut) {
        this.rut = rut;
    }

    public short getPresentoRut() {
        return this.presentoRut;
    }

    public void setPresentoRut(short presentoRut) {
        this.presentoRut = presentoRut;
    }

    public short getPresentoCedula() {
        return this.presentoCedula;
    }

    public void setPresentoCedula(short presentoCedula) {
        this.presentoCedula = presentoCedula;
    }

    public short getPresntoHv() {
        return this.presntoHv;
    }

    public void setPresntoHv(short presntoHv) {
        this.presntoHv = presntoHv;
    }

    public short getPresentoEntrevista() {
        return this.presentoEntrevista;
    }

    public void setPresentoEntrevista(short presentoEntrevista) {
        this.presentoEntrevista = presentoEntrevista;
    }

    public Set getCuentaBancarias() {
        return this.cuentaBancarias;
    }

    public void setCuentaBancarias(Set cuentaBancarias) {
        this.cuentaBancarias = cuentaBancarias;
    }

    /**
     * @return the login
     */
    public String getLogin() {
        return login;
    }

    /**
     * @param login the login to set
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * @return the contrasena
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * @param contrasena the contrasena to set
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * @return the contratos
     */
    public //MIOS
            List<Contrato> getContratos() {
        return contratos;
    }

    /**
     * @param contratos the contratos to set
     */
    public void setContratos(List<Contrato> contratos) {
        this.contratos = contratos;
    }

    /**
     * @return the cuentaBancariaVOs
     */
    public List<CuentaBancariaVO> getCuentaBancariaVOs() {
        return cuentaBancariaVOs;
    }

    /**
     * @param cuentaBancariaVOs the cuentaBancariaVOs to set
     */
    public void setCuentaBancariaVOs(List<CuentaBancariaVO> cuentaBancariaVOs) {
        this.cuentaBancariaVOs = cuentaBancariaVOs;
    }
}


