package Entidades;
// Generated 19/11/2009 09:49:40 PM by Hibernate Tools 3.2.1.GA



/**
 * RegtroValRtencion generated by hbm2java
 */
public class RegtroValRtencion  implements java.io.Serializable {


     private int id;
     private int idCauscionPs;
     private double valorRetencion;
     private int idRetncionPago;

    public RegtroValRtencion() {
    }

    public RegtroValRtencion(int id, int idCauscionPs, double valorRetencion, int idRetncionPago) {
       this.id = id;
       this.idCauscionPs = idCauscionPs;
       this.valorRetencion = valorRetencion;
       this.idRetncionPago = idRetncionPago;
    }

    public RegtroValRtencion(int idCauscionPs, double valorRetencion, int idRetncionPago) {
       
       this.idCauscionPs = idCauscionPs;
       this.valorRetencion = valorRetencion;
       this.idRetncionPago = idRetncionPago;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdCauscionPs() {
        return this.idCauscionPs;
    }
    
    public void setIdCauscionPs(int idCauscionPs) {
        this.idCauscionPs = idCauscionPs;
    }
    public double getValorRetencion() {
        return this.valorRetencion;
    }
    
    public void setValorRetencion(double valorRetencion) {
        this.valorRetencion = valorRetencion;
    }
    public int getIdRetncionPago() {
        return this.idRetncionPago;
    }
    
    public void setIdRetncionPago(int idRetncionPago) {
        this.idRetncionPago = idRetncionPago;
    }




}


