package Entidades;
// Generated 5/11/2009 04:41:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RetencionPagos generated by hbm2java
 */
public class RetencionPagos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double porcentaje;
     private Date fechaExpiracion;
     private short vigente;
     private Set vfpRetPagoses = new HashSet(0);

    public RetencionPagos() {
    }

    public RetencionPagos(int id) {
        this.id = id;
    }

	
    public RetencionPagos(int id, String nombre, double porcentaje, Date fechaExpiracion, short vigente) {
        this.id = id;
        this.nombre = nombre;
        this.porcentaje = porcentaje;
        this.fechaExpiracion = fechaExpiracion;
        this.vigente = vigente;
    }
    public RetencionPagos(int id, String nombre, double porcentaje, Date fechaExpiracion, short vigente, Set vfpRetPagoses) {
       this.id = id;
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.fechaExpiracion = fechaExpiracion;
       this.vigente = vigente;
       this.vfpRetPagoses = vfpRetPagoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public short getVigente() {
        return this.vigente;
    }
    
    public void setVigente(short vigente) {
        this.vigente = vigente;
    }
    public Set getVfpRetPagoses() {
        return this.vfpRetPagoses;
    }
    
    public void setVfpRetPagoses(Set vfpRetPagoses) {
        this.vfpRetPagoses = vfpRetPagoses;
    }




}


