package Entidades;
// Generated 19/10/2009 12:36:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Retenciones generated by hbm2java
 */
public class Retenciones  implements java.io.Serializable {

     private short id;
     private String nombre;
     private String porcentaje;
     private Set facturaRetencions = new HashSet(0);

     //No pertenece a la tabla de retenciones
     private double valor;
    public Retenciones() {
    }

    public Retenciones(String nombre, String porcentaje) {
        this.nombre = nombre;
        this.porcentaje = porcentaje;
    }
    public Retenciones(short id) {
        this.id = id;
       
    }
    public Retenciones(short id, String nombre, String porcentaje) {
        this.id = id;
        this.nombre = nombre;
        this.porcentaje = porcentaje;
    }
    public Retenciones(short id, String nombre, String porcentaje, Set facturaRetencions) {
       this.id = id;
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.facturaRetencions = facturaRetencions;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(String porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set getFacturaRetencions() {
        return this.facturaRetencions;
    }
    
    public void setFacturaRetencions(Set facturaRetencions) {
        this.facturaRetencions = facturaRetencions;
    }

    /**
     * @return the valor
     */
    public //No pertenece a la tabla de retenciones
    double getValor() {
        return valor;
    }

    /**
     * @param valor the valor to set
     */
    public void setValor(double valor) {
        this.valor = valor;
    }




}


