package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA



/**
 * RolPermisos generated by hbm2java
 */
public class RolPermisos  implements java.io.Serializable {


     private int id;
     private Rol rol;
     private Permisos permisos;

    public RolPermisos() {
    }

    public RolPermisos(int id, Rol rol, Permisos permisos) {
       this.id = id;
       this.rol = rol;
       this.permisos = permisos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }




}


