package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA



/**
 * Soporte generated by hbm2java
 */
public class Soporte  implements java.io.Serializable {


     private int id;
     private Movimientos movimientos;

    public Soporte() {
    }

	
    public Soporte(int id) {
        this.id = id;
    }
    public Soporte(int id, Movimientos movimientos) {
       this.id = id;
       this.movimientos = movimientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Movimientos getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Movimientos movimientos) {
        this.movimientos = movimientos;
    }




}


