package Entidades;
// Generated 6/12/2009 05:49:01 PM by Hibernate Tools 3.2.1.GA



/**
 * Tablas generated by hbm2java
 */
public class Tablas  implements java.io.Serializable {


     private int id;
     private String nombreTabla;

    public Tablas() {
    }

    public Tablas(int id, String nombreTabla) {
       this.id = id;
       this.nombreTabla = nombreTabla;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreTabla() {
        return this.nombreTabla;
    }
    
    public void setNombreTabla(String nombreTabla) {
        this.nombreTabla = nombreTabla;
    }




}


