package Entidades;
// Generated 6/12/2009 05:46:09 PM by Hibernate Tools 3.2.1.GA



/**
 * TablaAtributo generated by hbm2java
 */
public class TablaAtributo  implements java.io.Serializable {


     private String code;
     private int idTabla;
     private Integer idCampo;
     private String nombre;
     private String nombreAtributo;

    public TablaAtributo() {
    }

	
    public TablaAtributo(String code, int idTabla, String nombre, String nombreAtributo) {
        this.code = code;
        this.idTabla = idTabla;
        this.nombre = nombre;
        this.nombreAtributo = nombreAtributo;
    }
    public TablaAtributo(String code, int idTabla, Integer idCampo, String nombre, String nombreAtributo) {
       this.code = code;
       this.idTabla = idTabla;
       this.idCampo = idCampo;
       this.nombre = nombre;
       this.nombreAtributo = nombreAtributo;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }
    public Integer getIdCampo() {
        return this.idCampo;
    }
    
    public void setIdCampo(Integer idCampo) {
        this.idCampo = idCampo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreAtributo() {
        return this.nombreAtributo;
    }
    
    public void setNombreAtributo(String nombreAtributo) {
        this.nombreAtributo = nombreAtributo;
    }




}


