package Entidades;
// Generated 24/11/2009 11:20:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TerminacionContrato generated by hbm2java
 */
public class TerminacionContrato  implements java.io.Serializable {


     private int id;
     private int idContrato;
     private short solicitante;
     private String motivo;
     private short cartaRenuncia;
     private short cartaAceptacion;
     private short cartaTerminacion;
     private Date fechaPropuestaRetiro;
     private Date fechaRetiro;
     private short respuesta;

    public TerminacionContrato() {
    }

    public TerminacionContrato(int id, int idContrato, short solicitante, String motivo, short cartaRenuncia, short cartaAceptacion, short cartaTerminacion, Date fechaPropuestaRetiro, Date fechaRetiro, short respuesta) {
       this.id = id;
       this.idContrato = idContrato;
       this.solicitante = solicitante;
       this.motivo = motivo;
       this.cartaRenuncia = cartaRenuncia;
       this.cartaAceptacion = cartaAceptacion;
       this.cartaTerminacion = cartaTerminacion;
       this.fechaPropuestaRetiro = fechaPropuestaRetiro;
       this.fechaRetiro = fechaRetiro;
       this.respuesta = respuesta;
    }

    public TerminacionContrato(int idContrato, short solicitante, String motivo, short cartaRenuncia, short cartaAceptacion, short cartaTerminacion, Date fechaPropuestaRetiro, Date fechaRetiro, short respuesta) {
       this.idContrato = idContrato;
       this.solicitante = solicitante;
       this.motivo = motivo;
       this.cartaRenuncia = cartaRenuncia;
       this.cartaAceptacion = cartaAceptacion;
       this.cartaTerminacion = cartaTerminacion;
       this.fechaPropuestaRetiro = fechaPropuestaRetiro;
       this.fechaRetiro = fechaRetiro;
       this.respuesta = respuesta;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public short getSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(short solicitante) {
        this.solicitante = solicitante;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public short getCartaRenuncia() {
        return this.cartaRenuncia;
    }
    
    public void setCartaRenuncia(short cartaRenuncia) {
        this.cartaRenuncia = cartaRenuncia;
    }
    public short getCartaAceptacion() {
        return this.cartaAceptacion;
    }
    
    public void setCartaAceptacion(short cartaAceptacion) {
        this.cartaAceptacion = cartaAceptacion;
    }
    public short getCartaTerminacion() {
        return this.cartaTerminacion;
    }
    
    public void setCartaTerminacion(short cartaTerminacion) {
        this.cartaTerminacion = cartaTerminacion;
    }
    public Date getFechaPropuestaRetiro() {
        return this.fechaPropuestaRetiro;
    }
    
    public void setFechaPropuestaRetiro(Date fechaPropuestaRetiro) {
        this.fechaPropuestaRetiro = fechaPropuestaRetiro;
    }
    public Date getFechaRetiro() {
        return this.fechaRetiro;
    }
    
    public void setFechaRetiro(Date fechaRetiro) {
        this.fechaRetiro = fechaRetiro;
    }
    public short getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(short respuesta) {
        this.respuesta = respuesta;
    }




}


