package Entidades;
// Generated 6/12/2009 05:44:17 PM by Hibernate Tools 3.2.1.GA



/**
 * TipoFormula generated by hbm2java
 */
public class TipoFormula  implements java.io.Serializable {


     private int id;
     private String nombre;

    public TipoFormula() {
    }

    public TipoFormula(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


