package Entidades;
// Generated 25/11/2009 03:04:37 PM by Hibernate Tools 3.2.1.GA



/**
 * TipoFicha generated by hbm2java
 */
public class TipoFicha  implements java.io.Serializable {


     private short id;
     private String nombre;

    public TipoFicha() {
    }

    public TipoFicha(short id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


