package Entidades;
// Generated 4/11/2009 10:54:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposContrato generated by hbm2java
 */
public class TiposContrato  implements java.io.Serializable {


     private short id;
     private String tipoContrato;
     private Set contratos = new HashSet(0);

    public TiposContrato() {
    }

	
    public TiposContrato(short id, String tipoContrato) {
        this.id = id;
        this.tipoContrato = tipoContrato;
    }
    public TiposContrato(short id, String tipoContrato, Set contratos) {
       this.id = id;
       this.tipoContrato = tipoContrato;
       this.contratos = contratos;
    }

    public TiposContrato(short id) {
       this.id = id;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(String tipoContrato) {
        this.tipoContrato = tipoContrato;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


