package Entidades;
// Generated 10/11/2009 06:00:21 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAsocaja generated by hbm2java
 */
public class TipoAsocaja  implements java.io.Serializable {


     private short id;
     private String nombre;
     private Set valoresAsocajas = new HashSet(0);
     private ValoresAsocaja unicoValAsocaja;

    public TipoAsocaja(short id) {
        this.id = id;
    }

    
     public TipoAsocaja() {
    }

	
    public TipoAsocaja(short id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoAsocaja(short id, String nombre, Set valoresAsocajas) {
       this.id = id;
       this.nombre = nombre;
       this.valoresAsocajas = valoresAsocajas;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getValoresAsocajas() {
        return this.valoresAsocajas;
    }
    
    public void setValoresAsocajas(Set valoresAsocajas) {
        this.valoresAsocajas = valoresAsocajas;
    }

    /**
     * @return the unicoValAsocaja
     */
    public ValoresAsocaja getUnicoValAsocaja() {
        return unicoValAsocaja;
    }

    /**
     * @param unicoValAsocaja the unicoValAsocaja to set
     */
    public void setUnicoValAsocaja(ValoresAsocaja unicoValAsocaja) {
        this.unicoValAsocaja = unicoValAsocaja;
    }




}


