package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoMovimiento generated by hbm2java
 */
public class TipoMovimiento  implements java.io.Serializable {


     private short id;
     private String nombre;
     private Set movimientoses = new HashSet(0);

    public TipoMovimiento() {
    }

	
    public TipoMovimiento(short id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoMovimiento(short id, String nombre, Set movimientoses) {
       this.id = id;
       this.nombre = nombre;
       this.movimientoses = movimientoses;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }




}


