package Entidades;
// Generated 26/10/2009 11:06:54 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCuentaBancaria generated by hbm2java
 */
public class TipoCuentaBancaria  implements java.io.Serializable {


     private short id;
     private String nombre;
     private Set cuentaBancarias = new HashSet(0);

    public TipoCuentaBancaria(short id) {
        this.id = id;
    }


    public TipoCuentaBancaria() {
    }

	
    public TipoCuentaBancaria(short id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoCuentaBancaria(short id, String nombre, Set cuentaBancarias) {
       this.id = id;
       this.nombre = nombre;
       this.cuentaBancarias = cuentaBancarias;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCuentaBancarias() {
        return this.cuentaBancarias;
    }
    
    public void setCuentaBancarias(Set cuentaBancarias) {
        this.cuentaBancarias = cuentaBancarias;
    }




}


