package Entidades;
// Generated 9/11/2009 07:01:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tributaria generated by hbm2java
 */
public class Tributaria  implements java.io.Serializable {


     private int id;
     private int ano;
     private Date fechaResolucion;
     private double smlv;
     private double auxilioTrasporte;
     private Set causacionNominas = new HashSet(0);

    public Tributaria() {
    }

    public Tributaria(int id) {
        this.id = id;
    }
	
    public Tributaria(int id, int ano, Date fechaResolucion, double smlv, double auxilioTrasporte) {
        this.id = id;
        this.ano = ano;
        this.fechaResolucion = fechaResolucion;
        this.smlv = smlv;
        this.auxilioTrasporte = auxilioTrasporte;
    }
    public Tributaria(int id, int ano, Date fechaResolucion, double smlv, double auxilioTrasporte, Set causacionNominas) {
       this.id = id;
       this.ano = ano;
       this.fechaResolucion = fechaResolucion;
       this.smlv = smlv;
       this.auxilioTrasporte = auxilioTrasporte;
       this.causacionNominas = causacionNominas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public Date getFechaResolucion() {
        return this.fechaResolucion;
    }
    
    public void setFechaResolucion(Date fechaResolucion) {
        this.fechaResolucion = fechaResolucion;
    }
    public double getSmlv() {
        return this.smlv;
    }
    
    public void setSmlv(double smlv) {
        this.smlv = smlv;
    }
    public double getAuxilioTrasporte() {
        return this.auxilioTrasporte;
    }
    
    public void setAuxilioTrasporte(double auxilioTrasporte) {
        this.auxilioTrasporte = auxilioTrasporte;
    }
    public Set getCausacionNominas() {
        return this.causacionNominas;
    }
    
    public void setCausacionNominas(Set causacionNominas) {
        this.causacionNominas = causacionNominas;
    }




}


