package Entidades;
// Generated 2/09/2009 03:44:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioSys generated by hbm2java
 */
public class UsuarioSys  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private int cedula;
     private String login;
     private String contrasena;
     private String correoElectronico;
     private short isAdmin;
     private Set notificacionCajaMenors = new HashSet(0);
     private Set usuarioSistemaRols = new HashSet(0);

    public UsuarioSys() {
    }

    public UsuarioSys(int id)
    {
        this.id = id;
      
    }
	
    public UsuarioSys(int id, String nombre, String apellido, int cedula, String login, String contrasena, String correoElectronico, short isAdmin) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.login = login;
        this.contrasena = contrasena;
        this.correoElectronico = correoElectronico;
        this.isAdmin = isAdmin;
    }
    public UsuarioSys(int id, String nombre, String apellido, int cedula, String login, String contrasena, String correoElectronico, short isAdmin, Set notificacionCajaMenors, Set usuarioSistemaRols) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.login = login;
       this.contrasena = contrasena;
       this.correoElectronico = correoElectronico;
       this.isAdmin = isAdmin;
       this.notificacionCajaMenors = notificacionCajaMenors;
       this.usuarioSistemaRols = usuarioSistemaRols;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public short getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(short isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getNotificacionCajaMenors() {
        return this.notificacionCajaMenors;
    }
    
    public void setNotificacionCajaMenors(Set notificacionCajaMenors) {
        this.notificacionCajaMenors = notificacionCajaMenors;
    }
    public Set getUsuarioSistemaRols() {
        return this.usuarioSistemaRols;
    }
    
    public void setUsuarioSistemaRols(Set usuarioSistemaRols) {
        this.usuarioSistemaRols = usuarioSistemaRols;
    }




}


