package Entidades;
// Generated 6/12/2009 05:51:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Valores generated by hbm2java
 */
public class Valores  implements java.io.Serializable {


     private int id;
     private String nombre;
     private double valor;
     private Date fecha;

    public Valores() {
    }

    public Valores(int id, String nombre, double valor, Date fecha) {
       this.id = id;
       this.nombre = nombre;
       this.valor = valor;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


