package Entidades;
// Generated 4/11/2009 10:54:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * ValorFormaPago generated by hbm2java
 */
public class ValorFormaPago  implements java.io.Serializable {


     private int id;
     private Contrato contrato;
     private TipoPago tipoPago;
     private String concepto;
     private String observacion;
     private short periodoPago;
     private Date fechaInicioPago;
     private short esFavorito;
     private double valorPago;
     private double totalPago;
     private Set fechasPagos = new HashSet(0);
     private List<RetencionPagos> retencionPagoses;
     private short esIbc;
     //MIOS
     private List<FechasPago> listaFechasPagos;
     private String nombreTipoPago;

    public ValorFormaPago() {
    }

    public ValorFormaPago( int id) {
        this.id = id;
    }
	
    public ValorFormaPago(int id, Contrato contrato, TipoPago tipoPago, String concepto, String observacion, short periodoPago, Date fechaInicioPago, short esFavorito, double valorPago, double totalPago) {
        this.id = id;
        this.contrato = contrato;
        this.tipoPago = tipoPago;
        this.concepto = concepto;
        this.observacion = observacion;
        this.periodoPago = periodoPago;
        this.fechaInicioPago = fechaInicioPago;
        this.esFavorito = esFavorito;
        this.valorPago = valorPago;
        this.totalPago = totalPago;
    }
    public ValorFormaPago(int id, Contrato contrato, TipoPago tipoPago, String concepto, String observacion, short periodoPago, Date fechaInicioPago, short esFavorito, double valorPago, double totalPago, Set fechasPagos) {
       this.id = id;
       this.contrato = contrato;
       this.tipoPago = tipoPago;
       this.concepto = concepto;
       this.observacion = observacion;
       this.periodoPago = periodoPago;
       this.fechaInicioPago = fechaInicioPago;
       this.esFavorito = esFavorito;
       this.valorPago = valorPago;
       this.totalPago = totalPago;
       this.fechasPagos = fechasPagos;
    }

    public ValorFormaPago( TipoPago tipoPago, String concepto, String observacion, short periodoPago, Date fechaInicioPago, short esFavorito, double valorPago, Set fechasPagos,List<RetencionPagos> retencionPagoses) {

       this.tipoPago = tipoPago;
       this.concepto = concepto;
       this.observacion = observacion;
       this.periodoPago = periodoPago;
       this.fechaInicioPago = fechaInicioPago;
       this.esFavorito = esFavorito;
       this.valorPago = valorPago;
       this.retencionPagoses = retencionPagoses;
       this.fechasPagos = fechasPagos;
    }


    public ValorFormaPago(int id, TipoPago tipoPago, String concepto, String observacion, short periodoPago, Date fechaInicioPago, short esFavorito, double valorPago,Contrato contrato) {

       this.id = id;
       this.tipoPago = tipoPago;
       this.concepto = concepto;
       this.observacion = observacion;
       this.periodoPago = periodoPago;
       this.fechaInicioPago = fechaInicioPago;
       this.esFavorito = esFavorito;
       this.valorPago = valorPago;
       this.contrato = contrato;
       
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public short getPeriodoPago() {
        return this.periodoPago;
    }
    
    public void setPeriodoPago(short periodoPago) {
        this.periodoPago = periodoPago;
    }
    public Date getFechaInicioPago() {
        return this.fechaInicioPago;
    }
    
    public void setFechaInicioPago(Date fechaInicioPago) {
        this.fechaInicioPago = fechaInicioPago;
    }
    public short getEsFavorito() {
        return this.esFavorito;
    }
    
    public void setEsFavorito(short esFavorito) {
        this.esFavorito = esFavorito;
    }
    public double getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(double valorPago) {
        this.valorPago = valorPago;
    }
    public double getTotalPago() {
        return this.totalPago;
    }
    
    public void setTotalPago(double totalPago) {
        this.totalPago = totalPago;
    }
    public Set getFechasPagos() {
        return this.fechasPagos;
    }
    
    public void setFechasPagos(Set fechasPagos) {
        this.fechasPagos = fechasPagos;
    }

    /**
     * @return the retencionPagoses
     */
    public List<RetencionPagos> getRetencionPagoses() {
        return retencionPagoses;
    }

    /**
     * @param retencionPagoses the retencionPagoses to set
     */
    public void setRetencionPagoses(List<RetencionPagos> retencionPagoses) {
        this.retencionPagoses = retencionPagoses;
    }

    /**
     * @return the esIbc
     */
    public short getEsIbc() {
        return esIbc;
    }

    /**
     * @param esIbc the esIbc to set
     */
    public void setEsIbc(short esIbc) {
        this.esIbc = esIbc;
    }

    /**
     * @return the listaFechasPagos
     */
    public List<FechasPago> getListaFechasPagos() {
        return listaFechasPagos;
    }

    /**
     * @param listaFechasPagos the listaFechasPagos to set
     */
    public void setListaFechasPagos(List<FechasPago> listaFechasPagos) {
        this.listaFechasPagos = listaFechasPagos;
    }

    /**
     * @return the nombreTipoPago
     */
    public String getNombreTipoPago() {
        return nombreTipoPago;
    }

    /**
     * @param nombreTipoPago the nombreTipoPago to set
     */
    public void setNombreTipoPago(String nombreTipoPago) {
        this.nombreTipoPago = nombreTipoPago;
    }




}


